title: A Course on Fairness, Accountability and Transparency in Machine Learning
description: Sponsored by the GIAN program of the Government of India
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
